apiVersion: v1
kind: Service
metadata:
  name: members
spec:
  selector:
    app: users
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: members
spec:
  selector:
    matchLabels:
      app: members
  replicas: 1
  template:
    metadata:
      labels:
        app: members
    spec:
      containers:
        - name: server
          image: blasphem0us/service-users-disciplines:latest
          ports:
            - name: http
              containerPort: 8083